[Film/#234] 아바타 컴포넌트 그룹의 최대 갯수 제한 및 클릭이벤트 추가
prgrms-web-devcourse/Team_17TOP_Film_FE pull request #235
Opened 2022-01-13 10:44 UTC by jinn2u

1. 아바타그룹의 최대 갯수 제한하기
    - maxLen 속성으로 제어할 수 있습니다.
    - 아바타의 갯수가 maxLen 보다 큰 경우에만  ... 표시가 나옵니다.
2. 아바타그룹에서 클릭 이벤트 주기
3. 아바타 컴포넌트에서 클릭 이벤트 주기

## 📌 리뷰 시 참고 사항
1. Image컴포넌트를 사용하여 avatar컴포넌트를 만들었는데 Props가 거의 비슷하였습니다. 따라서  Omit을 사용해 사용하지 않는 prop들은 제어하는 방식으로 만들었는데 
[문제]
이렇게 한다면avatar에서 모든 props가 optional로 되는것 같습니다. 더 좋은 방법이 있을까욤..?
2. maxLen보다 avatar의 갯수가 많은 경우
    1. ... 을 아바타 맨 끝에 붙여줄 때 Image에서 relative속성이 적용이 되지 않아 갯수만큼 margin을 주었습니다. 
    2. 맨마지막의 경우는 grayScale을 해서 앞의 avatar와 다른것을 시각적으로 보여주었습니다. 
    3. ...을 사용할 때 배경이 흰색이거나 검은 색인 경우 보이지 않을것 같아 border는 black으로, background는 white로 주었습니다.
    위와 같은 방식으로 만들었는데 더 좋은 의견 있을까요??

2022-01-17 06:39 UTC, 2sjeong918 commented
리뷰시 참고사항 1번이 제가 돌려봤을 때는 필수 속성은 잘 체크하는 것 같습니다! 
size를 넣지 않고 Avatar컴포넌트를 만들면 에러가 잘 나옵니다!

2022-01-17 07:10 UTC, 2sjeong918 requested changes

2022-01-17 07:10 UTC, 2sjeong918 commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +  justify-content: space-between;
`justify-content: space-around;`로 하면 좌우 양쪽에도 여백이 생겨서 더 좋을 것 같습니다!

2022-01-17 07:10 UTC, 2sjeong918 commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +`;
이미지가 없는 경우에 placeholder 이미지가 나오는데 흑백 아이콘 이미지라 grayScale보다 `filter: brightness(0.5);` 로 약간 어둡게 처리하면 어떨까 싶습니다!

2022-01-17 07:10 UTC, 2sjeong918 commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +  margin-top: ${({ size }) => `-${size / 2 + (size * 0.1) / 2}px`};
<img width="349" alt="스크린샷 2022-01-17 오후 4 05 40" src="https://user-images.githubusercontent.com/28250027/149723069-e6164fe7-5629-49b4-858a-7e06d28dd3bd.png">
margin-top을 음수로 줘서 그런지 아바타 그룹의 높이가 줄어들어서 인식되는 것 같아요! 컴포넌트 사용시에 레이아웃을 잡기 까다로워질 수도 있을 것 같아서 해당 높이가 아바타 높이와 동일하게 인식될 수 있으면 좋을 것 같습니다!

2022-01-17 07:10 UTC, 2sjeong918 commented on src/components/refactor/atoms/Avatar/AvatarGroup/index.tsx
> +      )}
지니의 노력이 보이는군요...!👍

2022-01-17 08:09 UTC, palsa131 reviewed
고생하셨습니다.

2022-01-17 08:09 UTC, palsa131 commented on src/components/refactor/atoms/Avatar/index.tsx
> +export interface Props extends Omit<ImgProps, 'height' | 'width' | 'borderRadius' | 'block'> {
여기 부분을 따로 type으로 빼서
```javascript
type Aprops = Omit<ImgProps, 'height' | 'width' | 'borderRadius' | 'block'> &
  Pick<Required<ImgProps>, 'src' | 'alt'>;
```
이런식으로 필요 속성만 따로 pick으로 required로 만들어서 가져오는 작성이 가능 하기는 합니다만 이러면 차라리 Props에서 새로 선언해서 덮어씌우는 것이 더 나을 수도 있겠네요 
(extends에서는 &를 사용해서 연결이 안되더라구요)

2022-01-18 07:51 UTC, jinn2u commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +  justify-content: space-between;
이 부분을 생각하지 못했네요~!! 수정했습니다 :)

2022-01-18 07:52 UTC, jinn2u commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +`;
반영했습니다~!

2022-01-18 09:03 UTC, jinn2u commented on src/components/refactor/atoms/Avatar/AvatarGroup/style.ts
> +  margin-top: ${({ size }) => `-${size / 2 + (size * 0.1) / 2}px`};
Wrapper에 `position: relative`를, CircleGroup에 `position: absolute`를 주어 해결했습니다~!

2022-01-26 07:39 UTC, 2sjeong918 approved these changes

2022-01-26 08:53 UTC, merged