[Film/#231] Input 컴포넌트 제작
prgrms-web-devcourse/Team_17TOP_Film_FE pull request #237
Opened 2022-01-17 05:52 UTC by palsa131

## 📝 작업한 내용

Input 컴포넌트를 제작 했습니다.

기본적인 디자인을 통일하기 위하여 작성 하였습니다.

### 속성
invalid? : boolean,  || false
width? : string | number  || 100%
borderRadius? : string | number || 4px

세 속성 모두 값을 입력하지 않으면 기본값으로 입력 됩니다.

속성 별 스토리 북 작성 하였습니다.

## 📷 화면 사진
<img width="718" alt="image" src="https://user-images.githubusercontent.com/68111046/149714996-b39cbedd-c8d1-4f9a-8984-f4938603bcb0.png">

2022-01-17 06:18 UTC, jinn2u commented on src/components/refactor/atoms/Input/style.ts
> +  width: string | number | undefined;
```width?: string | number```로 작성해도 똑같은것 같네요~!

2022-01-17 06:37 UTC, jinn2u reviewed
다음부터는 이전과 달라진점도 pr올릴때 써주신다면 더 보기 편할것 같습니다~!

2022-01-17 06:37 UTC, jinn2u commented on src/components/refactor/atoms/Input/style.ts
> +  width: string | number | undefined;
```width?: string | number```로 작성해도 똑같은것 같네요~!

2022-01-17 06:37 UTC, jinn2u commented on src/components/refactor/atoms/Input/style.ts
> +  ::placeholder {
&를 사용하지 않아도 잘 되는군요...!👀

2022-01-17 06:37 UTC, jinn2u commented on src/components/refactor/atoms/Input/types.ts
> +export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
👍

2022-01-17 06:37 UTC, jinn2u commented on src/components/refactor/atoms/Input/index.tsx
> +  ref: ForwardedRef<HTMLInputElement>,
혹시 ref를 구조분해할당으로 받지 않은 이유가 있을까요??

2022-01-17 07:36 UTC, 2sjeong918 requested changes

2022-01-17 07:36 UTC, 2sjeong918 commented on src/components/refactor/atoms/Input/style.ts
> +  padding: 0 16px 0 16px;
위아래, 좌우가 같아서 `padding: 0 16px; `로 쓸 수 있을 것 같습니다!

2022-01-17 07:36 UTC, 2sjeong918 commented on src/components/refactor/atoms/Input/style.ts
> +  }
invalid 의 경우 focus가 되면 border를 primary컬러보다는 invalid 컬러와 동일하게 주는 것이 좋을 것 같습니다!

2022-01-17 07:36 UTC, 2sjeong918 commented on src/components/refactor/atoms/Input/index.tsx
> +        invalid={invalid}
invalid의 경우 input의 autofocus 속성을 활용해서 해당 input에 포커스가 가도록 해줄 수도 있을 것 같습니다! 다만 여러개의 invalid input이 있는 경우에는 문제가 생길 수도 있을 것 같긴하네요...ㅎㅎ

2022-01-17 10:24 UTC, palsa131 commented on src/components/refactor/atoms/Input/style.ts
> +  width: string | number | undefined;
앗 이전 커밋인거 같네요!

2022-01-17 10:24 UTC, palsa131 commented on src/components/refactor/atoms/Input/index.tsx
> +  ref: ForwardedRef<HTMLInputElement>,
forwardRef 사용을 위해서 입니다.

[forwardRef 참조 사이트입니다.](https://maybe-b50.tistory.com/63)

2022-01-18 07:44 UTC, jinn2u commented on src/components/refactor/atoms/Input/index.tsx
> +        invalid={invalid}
저도 그래서 input컴포넌트안에서 focus를 관리한다면 input컴포넌트들이 여러개 있다면 맨마지막에 focus가 갈것 같습니다~! 
따라서 input컴포넌트를 사용하는 쪽에서 focus속성을 ref로 부여하는게 더 좋아보입니다!

2022-01-18 08:08 UTC, merged